#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_MISC_2 30


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBAS	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN	4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_COLOR_PLATFORM 6
#define OBJECT_TYPE_QUESTION_BRICK 7
#define OBJECT_TYPE_SHOOTING_FLOWER 8
#define OBJECT_TYPE_TUBE 9
#define OBJECT_TYPE_FIRE_BULLET 10
#define OBJECT_TYPE_PORTAL	50


#pragma region BRICK 

#define ID_SPRITE_STRIPE_BRICK 19000
#define ID_SPRITE_BRICK 20000
#define ID_SPRITE_QBRICK 20500

#pragma endregion 


#pragma region COIN

#define ID_SPRITE_COIN 40000

#pragma endregion 

#pragma region MUSHROOM

#define ID_SPRITE_MUSHROOM_IN_BRICK 45000
#define ID_SPRITE_MUSHROOM_OUT_BRICK 45316

#pragma endregion 

#pragma region LEAF

#define ID_SPRITE_LEAF_RIGHT 60000
#define ID_SPRITE_LEAF_LEFT 60500

#pragma endregion 

#pragma region SHOOTING FLOWER

#define ID_SPRITE_SHOOTING_FLOWER_RISE_UP 80000
#define ID_SPRITE_SHOOTING_FLOWER_IDLE 81000

#pragma endregion 

#define ID_SPRITE_GROUND 400000

#define ID_SPRITE_TUBE 5400

#define ID_SPRITE_EFFECT_SCORE_100 100
#define ID_SPRITE_EFFECT_SCORE_2O0	200
#define ID_SPRITE_EFFECT_SCORE_4O0	400