#pragma region GOOMBA & PARA_GOOMBA

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)
#define ID_SPRITE_GOOMBA_DIE_REVERSE (ID_SPRITE_GOOMBA + 2001)

#define ID_SPRITE_PARA_GOOMBA 33000
#define ID_SPRITE_PARA_GOOMBA_WALK (ID_SPRITE_PARA_GOOMBA + 100)
#define ID_SPRITE_PARA_GOOMBA_DIE (ID_SPRITE_PARA_GOOMBA + 200)
#define ID_SPRITE_PARA_GOOMBA_DIE_REVERSE (ID_SPRITE_PARA_GOOMBA + 201)
#define ID_SPRITE_PARA_GOOMBA_FLY (ID_SPRITE_PARA_GOOMBA + 300)
#define ID_SPRITE_PARA_GOOMBA_CALM (ID_SPRITE_PARA_GOOMBA + 400)

#pragma endregion 