#pragma region KOOPA

#define ID_SPRITE_KOOPA 35000
#define ID_SPRITE_KOOPA_WALK_LEFT (ID_SPRITE_KOOPA + 1000)
#define ID_SPRITE_KOOPA_WALK_RIGHT (ID_SPRITE_KOOPA + 1500)
#define ID_SPRITE_KOOPA_SLEEP (ID_SPRITE_KOOPA + 2000)
#define ID_SPRITE_KOOPA_SLEEP_REVERSE (ID_SPRITE_KOOPA + 2500)
#define ID_SPRITE_KOOPA_SLIP (ID_SPRITE_KOOPA + 3000)
#define ID_SPRITE_KOOPA_SLIP_REVERSE (ID_SPRITE_KOOPA + 3500)
#define ID_SPRITE_KOOPA_DIE (ID_SPRITE_KOOPA + 4000)
#define ID_SPRITE_KOOPA_REBORN (ID_SPRITE_KOOPA + 5000)
#define ID_SPRITE_KOOPA_REBORN_REVERSE (ID_SPRITE_KOOPA + 5500)

#pragma endregion 

#pragma region KOOPA_PARA

#define ID_SPRITE_KOOPA_PARA 70000
#define ID_SPRITE_KOOPA_JUMPING_LEFT (ID_SPRITE_KOOPA_PARA + 1000)
#define ID_SPRITE_KOOPA_JUMPING_RIGHT (ID_SPRITE_KOOPA_PARA + 1500)
#define ID_SPRITE_KOOPA_PARA_SLEEP (ID_SPRITE_KOOPA_PARA + 2000)
#define ID_SPRITE_KOOPA_PARA_SLIP (ID_SPRITE_KOOPA_PARA + 3000)
#define ID_SPRITE_KOOPA_PARA_DIE (ID_SPRITE_KOOPA_PARA + 4000)
#define ID_SPRITE_KOOPA_PARA_REBORN (ID_SPRITE_KOOPA_PARA + 5000)
#define ID_SPRITE_KOOPA_PARA_REBORN_REVERSE (ID_SPRITE_KOOPA_PARA + 6000)

#pragma endregion #pragma once

#pragma region RED_KOOPA

#define ID_SPRITE_RED_KOOPA 105000
#define ID_SPRITE_RED_KOOPA_WALK_LEFT (ID_SPRITE_RED_KOOPA + 1000)
#define ID_SPRITE_RED_KOOPA_WALK_RIGHT (ID_SPRITE_RED_KOOPA + 1500)
#define ID_SPRITE_RED_KOOPA_SLEEP (ID_SPRITE_RED_KOOPA + 2000)
#define ID_SPRITE_RED_KOOPA_SLEEP_REVERSE (ID_SPRITE_RED_KOOPA + 2500)
#define ID_SPRITE_RED_KOOPA_SLIP (ID_SPRITE_RED_KOOPA + 3000)
#define ID_SPRITE_RED_KOOPA_SLIP_REVERSE (ID_SPRITE_RED_KOOPA + 3500)
#define ID_SPRITE_RED_KOOPA_DIE (ID_SPRITE_RED_KOOPA + 4000)
#define ID_SPRITE_RED_KOOPA_REBORN (ID_SPRITE_RED_KOOPA + 5000)
#define ID_SPRITE_RED_KOOPA_REBORN_REVERSE (ID_SPRITE_RED_KOOPA + 5500)

#pragma endregion 